/**
 * shadcn-vue 组件统一导出
 * 用法：import { Button, Card, CardHeader, CardTitle } from '@/components/ui'
 */
export { default as Button } from './Button.vue'
export { buttonVariants } from './button-variants'
export { default as Card } from './Card.vue'
export { default as CardHeader } from './CardHeader.vue'
export { default as CardTitle } from './CardTitle.vue'
export { default as CardDescription } from './CardDescription.vue'
export { default as CardContent } from './CardContent.vue'
export { default as CardFooter } from './CardFooter.vue'
export { default as Input } from './Input.vue'
export { default as Textarea } from './Textarea.vue'
export { default as Label } from './Label.vue'
export { default as Separator } from './Separator.vue'
export { default as Badge } from './Badge.vue'
export { default as Skeleton } from './Skeleton.vue'
export { default as Progress } from './Progress.vue'
export { default as Select } from './Select.vue'
export { default as Switch } from './Switch.vue'
export { default as DialogRoot } from './DialogRoot.vue'
export { default as DialogTrigger } from './DialogTrigger.vue'
export { default as DialogPortal } from './DialogPortal.vue'
export { default as DialogOverlay } from './DialogOverlay.vue'
export { default as DialogContent } from './DialogContent.vue'
export { default as DialogHeader } from './DialogHeader.vue'
export { default as DialogFooter } from './DialogFooter.vue'
export { default as DialogTitle } from './DialogTitle.vue'
export { default as DialogDescription } from './DialogDescription.vue'
export { default as Tooltip } from './Tooltip.vue'
export { default as TooltipProvider } from './TooltipProvider.vue'
export { default as Table } from './Table.vue'
export { default as TableHeader } from './TableHeader.vue'
export { default as TableBody } from './TableBody.vue'
export { default as TableRow } from './TableRow.vue'
export { default as TableHead } from './TableHead.vue'
export { default as TableCell } from './TableCell.vue'
export { default as ScrollArea } from './ScrollArea.vue'
export { default as DropdownMenu } from './DropdownMenu.vue'
export { default as DropdownMenuContent } from './DropdownMenuContent.vue'
export { default as DropdownMenuItem } from './DropdownMenuItem.vue'
export { default as DropdownMenuSeparator } from './DropdownMenuSeparator.vue'
export { default as DropdownMenuLabel } from './DropdownMenuLabel.vue'
export { default as Tabs } from './Tabs.vue'
export { default as TabsList } from './TabsList.vue'
export { default as TabsTrigger } from './TabsTrigger.vue'
export { default as TabsContent } from './TabsContent.vue'
